name: student-portal
region: sgp
static_sites:
  - name: student-portal
    build_command: npm run build
    output_dir: dist
    catchall_document: index.html
    envs:
      - key: VITE_API_URL
        value: ${backend-api.PUBLIC_URL}/api
        scope: RUN_AND_BUILD
